### ISSUE TITLE
Baseline as a Service Demo

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#10]
A small company can get a Docusign agreement, sign it, and get an offer to add a easy-to-use mini-system of record to baseline with the counterparty in the agreement...."for the low low price of $9.95 a month!"

**Comment by humbitious** [comment]
How's this going, Kyle?  Think we can have a demo of it by next Monday...or the following TSC/SSC meetings?

**Comment by kthomas** [comment]
> How's this going, Kyle? Think we can have a demo of it by next Monday...or the following TSC/SSC meetings?

It's going well and yes. Let's connect this week to decide timing for demos.

**Comment by danielnorkin** [comment]
@kthomas - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
