### ISSUE TITLE
Website evolution project: Add core decks and other collateral as downloadable directly from home page:

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#105]
From JoeVZ:  per my suggestion via today's SSC call. I'd suggest placing the emerging market development collateral on the Baseline top level domain as it's the top organic search result for Baseline Protocol.  The idea is that any curious business and/or technical stakeholder can have access to these materials and support market development efforts without having to search Github or join the Slack.

From Avia Kraft: Hi everyone! For anyone interested, the current drafts of the high level Baseline value deck and the aerospace use case deck are both attached here. Moreover, links to the Google Slides files are included below. We are taking active edits if you are interested in contributing to either project, please do help us improve them!
Google Slides Aerospace Deck: 
https://docs.google.com/presentation/d/1cY9Wo6Q7tgsCl90k4_W7AIk5Dqrj1WMbwxrY-IoZd5o/edit?usp=sharing
High Level Value Deck: 
https://docs.google.com/presentation/d/137jyhOwRnHhaJ8CUV03MJd-YT6FgTaUQ-CF1bqcQgSw/edit?usp=sharing

**Comment by Consianimis** [comment]
I have gone through the Aerospace slides to see if the use case template  (#103) was fit for purpose. Maybe it could benefit website visitors to access a dedicated Use cases page in addition to having core decks as downladable directly from home page.

<table>
<tr>
    <th>Use Case Name</th>
    <td>Establishing History for Life Limited Parts</td>
  </tr>
<tr>
    <th>Use Case Description</th>
    <td>what is the problem/challenge, how does the baseline protocol address it? </td>
  </tr>
<tr>
    <th>Industry/Vertical</th>
    <td>Aerospace</td>
  </tr>
<tr>
    <th>Enterprise Domain</th>
    <td>Supply Chain</td>
  </tr>
<tr>
    <th>Business Process</th>
    <td>Life limited parts traceability management</td>
  </tr>
<tr>
    <th>Systems</th>
    <td>Atennea Airport (Microsoft Dynamics NAV), AMC ERP Suite,IFS </td>
  </tr>
<tr>
    <th>Actors/Personas</th>
    <td>Carrier/Leaser (Owner), Mx Repair Station/OEM (Approved Manufacturer)</td>
  </tr>
<tr>
    <th>Key Components</th>
    <td>

- Data completeness through systems of record consistency
- Cost reduction 
- Industry compliance

</td>
  </tr>
<tr>
    <th>Link</th>
    <td>https://docs.google.com/presentation/d/1cY9Wo6Q7tgsCl90k4_W7AIk5Dqrj1WMbwxrY-IoZd5o/edit#slide=id.g8828a79d5d_2_0</td>
  </tr>
</table>
