### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#108]
This is a master epic to cover various research spikes and solutions to the need to increase on-chain confirmations of worksteps-per-minute/day/month by 10x to 100x in the 2021 timeframe.

**Comment by danielnorkin** [comment]
@CannotContainMyself - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
