### ISSUE TITLE
Hyperledger Avalon Integration

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#12]
The intention of this initiative is to find the right way to use HL Avalon (and/or related tech from the Linux Foundation Confidential Compute project) to run off chain processes in secure enclaves such that, via baselining, they are verifiably consistent. In this scheme, the message from an initiating Party would instruct counterparty systems to perform workflow steps as expected by the initiator while masking the workload request and results.

Work to be done here includes articulating a specific set of examples that would illustrate a canonical flow, so that we can talk about it more easily.

Also, creating a specification/"cookbook" for how one would wire up the Avalon components (workflow requestor, workers, etc). 

The timeframe for this work would ideally culminate in a significant milestone toward the end of 2020.

**Comment by gleim** [comment]
very early-stage analysis underway across organizations with @hadasz @danielnorkin

**Comment by humbitious** [comment]
Please advise whether we should move this to backlog or if it is still in-progress. Will review new and in-progress epics during the 7/20 SSC meeting.

**Comment by gleim** [comment]
As indicated in 7/20 SSC meeting, this is an issue under active development and there may be an update available to be presented at the 8/3 SSC meeting.

**Comment by danielnorkin** [comment]
@gleim - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
