### ISSUE TITLE
Baseline Summit: November 2020

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#129]
It was decided in the TSC and PGB to conduct a one or two-day online open summit to facilitate focused work on planning and designing the next items the protocol roadmap, including new protocol features, non-functional requirement work, demos, and community programs.

Please use comments to this Issue to add thoughts and agenda items for this planning effort.  Starting at the steering committee meeting on Monday, October 12, 2020, community members will hold weekly sessions to plan, prep and execute the summit, and we will use this issue to contain the work.

**Comment by humbitious** [comment]
This summit may form the basis for an upcoming Gitcoin-run hackathon event in December 2020, where the challenges that hackathon participants can compete to win bounties come out of the work from this Summit.

**Comment by humbitious** [comment]
##Summit Topic:  Next Companies, Products and Platforms that Should 'Baseline'

Examples:  Airtable, Intuit, Snowflake, Neo4J, Mongo

We should gather to triangulate on folks in our community who can help introduce baselining to these organizations and also to focus on making sure outreach is done, resulting in a) new contributors; b) new sponsors; c) new demos; d) new product announcements.

**Comment by Github-shipchain** [comment]
Proposal of agenda item: how to overcome Ethereum high fees and scale up using layer 2 aka sidechain.
ShipChain has some experience to share here. A state of the art of all available solutions with proper EVM compatibility would be great. 

Another interesting topic is how to become blockchain agnostic and how to leverage blockchain interoperability, foreseeing a future where there is not just one Ethereum mainnet but multiple blockchains with their pros and cons in terms of speed and decentralization, who will need to be able to communicate together and on which baselining should be made possible.

**Comment by Consianimis** [comment]
##Summit Topic: Baseline for CIOs - Create collaborative business processes via Public Blockchain.

It could be interesting to have a session focused on demonstrating business benefits and handling objections of integrating business processes across participating organizations using Ethereum Mainnet.
This could cover enterprise capabilities, service qualities etc.
