### ISSUE TITLE
Make LinkedIn Group a Vibrant Community for Baseline 

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#14]
The Baseline Community has a vigorous community on Twitter, Slack (and thanks to the connector between them, also Discord and Telegram), etc. 
We have a LinkedIn Group, but it is not used yet.

Acceptance criteria:  
- [ ] 100 members of the group have joined
- [ ] Regular weekly postings or better
- [ ] A known accountable person committed to keeping the group vibrant

**Comment by Sjaaaakster** [comment]
Good to see that a Linkedin group has been created. It would also be advisable to create a regular Linkedin account for Baseline to be able to post with it.

It is no problem for me to be an administrator in the group to accept new members.

Regular postings can be done with the baseline protocol account.

**Comment by Sjaaaakster** [comment]
update: Linkedin group has now around 100 members. 

My request is to try to have conversations with other members every now and then. I will take an active role in this myself, but it is good if this is done by several people.

There is also a function where you can invite people from your network to join the Baseline group.

I did this today which resulted in a large number of new members.

Action point that is still open is to create a corporate Baseline account on linkedin to post messages / news

**Comment by humbitious** [comment]
Outstanding! Let's mention this on Monday's SSC call, highlight the work, and then we can close this issue and declare success...and keep a tickler to ensure we are progressing from this milestone.

**Comment by humbitious** [comment]
I agree that we should create a corporate Baseline account on LinkedIn, because it seems that this is required to post basline community posts to the public (unless I'm missing something?)

**Comment by kyleellicott** [comment]
Agreed. Also having a business/corporate account will allow for including & tagging in future posts when referencing as well - if desired.
