### ISSUE TITLE
Tokenization of Baselined Records -- Methods and Practices

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#142]
## Project Description
This master epic will contain projects around the creation and management of digital assets based on baselined records.

Key Questions to answer:
- How to convert one or more baseline records/states into one or more onchain asset and how to properly define such an onchain asset aka which Token standard to choose for which baselined record(s)/state(s)?
- What are the options “where” (onchain or offchain or in both places) the asset can exist? 
- How to exit/import a baseline onchain asset from/into a baseline operating environment aka from Baseline Stack A <-> Baseline Stack B?
- How to integrate a baselined onchain asset into onchain asset protocols such as DeFi protocols?
- What are the interactions between a state change of a baselined record and its connected onchain asset and how do these interactions work?
- How to ensure secure tokenization of baselined records/state?
- How to ensure privacy in the tokenization of baselined records/state?

Below are references to get people started to participate in the discussion. Please, read!

- Good intro on how to use offchain data onchain: https://chain.link/presentations/english.pdf

- Token standards overview: https://docs.ethhub.io/built-on-ethereum/erc-token-standards/what-are-erc-tokens/#:~:text=ERCs%20(Ethereum%20Request%20for%20Comments,smart%20contract%20developers%20at%20Ethereum.&text=Before%20becoming%20an%20standard%2C%20an,EIP%20(Ethereum%20Improvement%20Proposal).

- How-to Introduction to standard token contracts: https://docs.openzeppelin.com/contracts/2.x/tokens

- Introduction on how to create new smart contracts (token contracts) from existing contracts: https://medium.com/upstate-interactive/creating-a-contract-with-a-smart-contract-bdb67c5c8595
 
- Upgrading Smart Contracts a why and how: https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable

- EIP 2353: Diamond Upgrade Pattern (most flexible): 
https://eips.ethereum.org/EIPS/eip-2535
https://github.com/mudgen/diamond  

## Impact on the Baseline Community
The state of systems of record has a direct impact on the financial health of a company.  The state of commercial records and contracts impact everything from cash flow to creditworthiness. Consequently, any option to a) ensure the correctness and provenance of commercial documents such as invoices and b) utilize this assurance to enter into financial contracts such as loans or repurchasing agreements to improve the financial situation of a company are immensely valuable. Especially if this can be done based both digitally and in real-time. This is where tokenization comes into play since tokenizing baselined commercial records allows the real-time, digital creation of financial contracts that can improve the financial position of a company in real-time. Therefore, adding tokenization capabilities to the baseline stack is of tremendous interest and importance to enterprises interested in Baseline.  

## Acceptance criteria and must have scope
Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this work.
Don't worry! This is not a commitment for a deadline. The timeframe can always change. Be bold and brave...make a guess. It helps focus volunteers and increases the chances of success, even if you wind up expanding the timeframe several times before completion.

---

[Background](https://help.zenhub.com/support/solutions/articles/43000010341) on Epics, Issues, Checkboxes (aka, Epics, Stories, Tasks)

After you start breaking this master epic up into a set of Issues (sub-epics, stories, tasks, etc), you might consider creating a Project in Github to make it easy for your group to have a single Kanban board for just this work. The Github projects tab in any given repo will allow only Issues from that repo, but if you create one [here](https://github.com/orgs/ethereum-oasis/projects), you will be able to set up a project that can compose Issues from any of the baseline repos, including the core /baseline repo and the planning /baseline-roadmap repo.

**Comment by Consianimis** [comment]
Question: How to convert one or more baseline records/states into one or more onchain asset and how to properly define such an onchain asset aka which Token standard to choose for which baselined record(s)/state(s)?

Idea: Evaluate relevance of zkERC20: Confidential Token Standard -  https://github.com/ethereum/EIPs/issues/1724

**Comment by marsrobertson** [comment]
If an invoice can be tokenized...

...maybe it can be put into escrow?

* A very good, related example: https://escrow.kleros.io/ (Kovan or Mainnet)
* Front-end: https://github.com/kleros/escrow
* Smart contracts: https://github.com/kleros/kleros-interaction/tree/master/contracts/standard/arbitration/MultipleArbitrableTokenTransaction.sol

### Money legos

![image](https://user-images.githubusercontent.com/44369284/98867439-6e41c400-2466-11eb-87e5-3e28c5af4c0a.png)

Invoices should be tokenized, obviously!
