### ISSUE TITLE
Baseline JVM

### ISSUE THREAD

**Issue by conor10** [eea-oasis/baseline-roadmap#146]
### This project is a suggestion in the #170 challenge for Hackathon 2020

It may be useful to have an implementation of the core Baseline Protocol on the Java Virtual Machine.

This would entail reimplementing what currently exists in JavaScript for the JVM.

As the [Baseline Specification](https://github.com/ethereum-oasis/baseline/blob/master/docs/specs/api/baseline-api-v1.0-psd01.md) evolves, it will serve as a reference for much of this work.

The end result would be that the Baseline messaging, persistence and privacy layers could run on a JVM runtime which would enable the protocol to take advantage of a whole number of well established enterprise integration platforms which are embedded within organisations.

As work has not yet started on this issue, it would be great for people to weigh in on this issue if they'd like to see this happen!

**Comment by humbitious** [comment]
I'm going to leave this in as a placeholder for a more general potential challenge to be reviewed with the TSC: Small bounties for pull requests of any kind that are accepted by Maintainers and merged to master during the hackathon period.

**Comment by GiraffeKey** [comment]
I may be interested in providing some initial setup and work for this.

Is it okay for this to be done in either Scala or Clojure? I much prefer them over Java.

Also something interesting to note is Scala.js and ClojureScript can possibly provide cross-compilation to JavaScript.
