### ISSUE TITLE
Gas Service

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#18]
"As the system administrator in a corporation that will not allow holding cryptocurrency to pay for baseline $gas transactions on the Mainnet, I need someone else to pay for the $gas and let me pay them in dollars (fiat) in such a way that the party paying the gas is not able to make transactions happen without me, tamper with my transactions, or collect information about my activities that would make them a security problem."

The method for providing a gas service in acceptable ways will require open source modifications to the baseline protocol factory contract and will likely add specification requirements.

**Comment by bitwiseguy** [comment]
Infura's ITX service aims to solve this problem. Currently in private alpha stage that still requires an on-chain ETH deposit. Future versions should allow fiat payments in place of ETH deposit.

https://infura.io/docs/transactions

**Comment by danielnorkin** [comment]
@breakpointer @humbitious @bitwiseguy @tjchmielewski @lookfirst - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.

**Comment by bitwiseguy** [comment]
@danielnorkin It looks like the ITX service is in the `beta` phase based on documentation here: https://infura.io/docs/transactions. The next major milestone will be achieved when ITX no longer requires users to deposit any ETH or test ETH on-chain (i.e. when it allows fiat payments instead)

**Comment by danielnorkin** [comment]
So keep it open?

**Comment by bitwiseguy** [comment]
Yes I think this Gas Service is still a work in-progress

**Comment by danielnorkin** [comment]
perfect, thanks!
