### ISSUE TITLE
Steering Committee Meeting Agenda and Minutes April 12, 2021

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#206]
Agenda:

1. Request additions to the agenda

2. Announce that the TSC voted to approve Tom Lyons' grant proposal

3. Announce that the TSC approved moving the Steering Committee meetings to once a month (in order to make more room in peoples' schedules for working groups like Standards, Maintainers (core devs now), Outreach and Grants.

4. Review Standards Committee 

5. Review Maintainers (discuss plan to run summit with the objective of completing v1.0 by 4Q or earlier)

6. Review Outreach team

7. Review status of ongoing Grants: https://github.com/ethereum-oasis/baseline-grants/issues

**Comment by GoldenBit0** [comment]
Moved to Baseline shared google drive - TSC folder
