### ISSUE TITLE
SAP<>Dynamics Integration Demonstration Video and Content

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#27]
The May 2020 demo of SAP/Dynamics integration via baselining is nearing completion. 

Goal is to ensure that a wide audience see and understand how this works, so that many people can get inspired and enabled to start integrating ERP/SCM systems.

Tasks:

-[ ] Record a live video meeting of Provide/Unibright/Envision, baselining a procurement process end-to-end (including working in the ERP systems) - 15 min

-[ ] Add a 45 minute panel discussion about what we saw, the potential for Enterprises and next steps, perhaps aiming at a more generic level than the technical details

-[ ] Write a press release

-[ ] Write blogs and tweets and share, share, share

**Comment by humbitious** [comment]
This is complete, yes?  Shall we close?

**Comment by danielnorkin** [comment]
Good to close
