### ISSUE TITLE
EY OpsChain Integration Kit

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#35]

**Comment by humbitious** [comment]
@skarred14 , this was a placeholder for tooling/kit to make it easy for folks to work with OpsChain. How would you like to proceed on this?  (What would someone that wanted to build baseline solutions with opschain need?  When would you think it would be good for OpsChain to have this connector kit available?)

**Comment by danielnorkin** [comment]
@skarred14 - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
