### ISSUE TITLE
Security Standards Guidelines

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#44]
**#Objective**
Provide security standards and security guidelines to relevant actors (systems and individuals).

**#Standards**
Security requirements - network security, security controls & monitoring, actors security responsabilities, access controls & permissioning, compliance & audit.

**#Guidelines**
Additional security & privacy considerations, recommended guidance based on experience and best practices.

**#Applicability**
Mainnet
Developers
Transaction Participants
Third Parties/External Parties

**Comment by danielnorkin** [comment]
@CannotContainMyself - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
