### ISSUE TITLE
Identity-Legal Workflow Demo With Everest and Docusign

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#50]

**Comment by humbitious** [comment]
He Stefan, Brad...should this go into icebox or backlog...or is it live?  If live, let's update and link to active issues.

**Comment by stefschmidt** [comment]
Hi John, I do not know why I was associated here, until know I have not been involved in this topic

**Comment by danielnorkin** [comment]
@bradleyjw @stefschmidt - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
