### ISSUE TITLE
Baseline in Manufacuring Demo

### ISSUE THREAD

**Issue by christianschmiedel** [eea-oasis/baseline-roadmap#56]
1. Triggering of the Raddish34 workflow by the process data from the machine control of a machine tool, e.g. to order maintenance service or spare parts.

2. Triggering the Raddish34 workflow with the condition of a verification of quality. The verification is based on the proof that the product is manufactured according to the agreed specifications and is demonstrated using 3D printing as an example.

**Comment by stefschmidt** [comment]
High-level description:

https://medium.com/unibrightio/unibright-and-fraunhofer-ipk-collaborate-on-baselining-additive-manufacturing-7469c36143a3

**Comment by humbitious** [comment]
Prepping for the SSC meeting tomorrow. How is status on this project? Should we keep in "in progress" column or move to backlog or icebox?

**Comment by stefschmidt** [comment]
It is in progress, we are working on it!Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: John Wolpert <notifications@github.com> Datum: 19.07.20  16:38  (GMT+01:00) An: ethereum-oasis/baseline-roadmap <baseline-roadmap@noreply.github.com> Cc: Stefan Schmidt <stefan.schmidt@jung-schmidt.de>, Assign <assign@noreply.github.com> Betreff: Re: [ethereum-oasis/baseline-roadmap] Baseline in Manufacuring Demo (#56) 
Prepping for the SSC meeting tomorrow. How is status on this project? Should we keep in "in progress" column or move to backlog or icebox?

**Comment by danielnorkin** [comment]
@kthomas @stefschmidt @christianschmiedel @marten42 @humbitious - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
