### ISSUE TITLE
Product UI and Record-Locking Kit

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#57]
Once a record in any system of record is "baselined" with records in other systems, it's important for users (and admins) to know that the record is baselined, so that, at minimum, the user sees a visual indication of the record's status and gets an alert before changes are committed, and at maximum, the record is locked to changes by the user and admin changes get a warning before changes are committed.  This is important, because if a baselined record is changed without going through a baseline change process ( see #58 ), the counterparties have "de-based" their record and must "rebase" ( #59 ) it.

**Comment by humbitious** [comment]
This kind of user experience would presumably require alteration to the application surfaced to the user (e.g., SAP, Dynamics, OpsChain)...certainly in the maximal case of having UI indications of baseline state and record-locking.  It is not required to baseline a record, and it is hoped that VARs like Envision can configure the user application suitably to help ensure that users don't change records...at least without awareness of the implications.

**Comment by humbitious** [comment]
Partially delivered in the Google sheets demo. Needs to be rendered into protocol level code.

**Comment by danielnorkin** [comment]
@humbitious - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
