### ISSUE TITLE
Enterprise Education - Baseline

### ISSUE THREAD

**Issue by amirardalan11** [eea-oasis/baseline-roadmap#71]
## Overview

Increase enterprise adoption of baseline technique through education and consulting

### Tasks

Step1: Create educational content that generates interest to learn more
Step2: More in-depth consulting to perform case-by-base study and onboard  new clients
Step3: Grow Baseline implementation and adoption

Hi, My name is Amir Razi. I'm the founder of Real E CHain. Real E Chain is an online platform that shares easy to understand classes about blockchain technology. -> www.realechain.com

Our first online course (blockchain 101) consists of 6 modules, one which is focused on the enterprise use case of the blockchain technology.  Each module will break down into more modules that dig deeper into the main topic. In the enterprise use case of the blockchain module, we can create more content about business and tech stack of baseline technique. 

The certificate from graduating from the program shows an essential preparedness to implement this technology. 

![Baseline courses.jpg](https://images.zenhubusercontent.com/5ecf377fe46988db68ad5571/e19f6133-3f86-4b75-bd26-5796cf6211da)[https://app.zenhub.com/files/258320699/df3c4d66-89b0-4150-be21-545908813480/download](https://app.zenhub.com/files/258320699/df3c4d66-89b0-4150-be21-545908813480/download)[https://app.zenhub.com/files/258320699/c745f097-85a2-4d38-bf9b-457c1689e39b/download](https://app.zenhub.com/files/258320699/c745f097-85a2-4d38-bf9b-457c1689e39b/download)

**Comment by humbitious** [comment]
Awesome. What's the next step? What do you need from the community?  Check in with @akraft-cc, @danielnorkin and others.
