### ISSUE TITLE
Regular Meeting Agendas and Minutes

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#88]
This epic is the container for meeting agendas and minutes for both the Technical Steering Committee as well as the Specifications Steering Committee, which usually meet every other week. Calendar entries for upcoming meetings are at: https://lists.oasis-open-projects.org/g/baseline/calendar.  

Unlike the weekly office hours, the Steering Committee meetings are by-invitation. If you wish to join one of the meetings, contact the [chair](https://docs.baseline-protocol.org/community/community-leaders#your-provisional-chair) either via [Slack](https://join.slack.com/t/ethereum-baseline/shared_invite/zt-d6emqeci-bjzBsXBqK4D7tBTZ40AEfQ) or directly.

All working group and committee minutes please include them in the comments of the next upcoming SC meeting.

All agendas and will be recorded as Issues in the /baseline-roadmap repo [here](https://github.com/ethereum-oasis/baseline-roadmap).

**Comment by sambacha** [comment]
Just to confirm this is happening at 11am EST correct? 

Thanks John, have a great weekend!

**Comment by KirkBallou** [comment]
@humbitious 
**Scaling discussion** 
This might be important for companies looking to use Baseline to understand even with Phase 0 Eth2.0 rollout how large scale / high tps applications should approach development. Without this direction you find several trying to do everything on the main chain. 
- Single applications will be limited to throughput per shard. (~100tps or whatever it ends up being).
   Not what the advertised total TPS is: 64 shards x TPS limit per shard.
- Outline trade offs of each Layer 2 or Off chain solution. (Example: PolkaDot/Kusama appears to have no DID / Identity based work currently. A team porting to use it might under estimate the work needed if this is not obvious to them.)

cc @kthomas
