### ISSUE TITLE
Using Oracles in Workflow Logic with Chainlink

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#89]
### Prize Bounty
ETH. Amount TBD on December 7, 2020.

### Challenge Description
Oracle systems like Chainlink aren't only useful in blockchain smart contracts. They are also important when running functions in multiple machines where dynamic input parameters like time, weather and prices must be verifiably identical in each instance. This is the case in baselined workflows, where each counterparty to a shared record (e.g., a purchase order, master service agreement or invoice) must run a workflow function on input data and get the same output deterministically.

Here are two [user stories](https://medium.com/baselineprotocol/how-the-baseline-protocol-integrates-chainlink-oracles-fc66be703c6e?source=friends_link&sk=392b60a5baff156bb12f3eea55d293e9) that highlight the role and function of an oracle in a baselined workflow, written by Chainlink's Johann Eid. Consider either of these and implement a minimally viable demonstration.  

Here also is a [video of Chainlink's demo](https://youtu.be/MFgUrCMIhnk) from the Baseline Protocol Summit on November 13, 2020.

### Submission Requirements
Produce a demonstration of any baselined workflow using the [BRI-1](https://github.com/ethereum-oasis/baseline/tree/master/examples/bri-1) library, but modify the business logic of at least one workstep to require a parameter whose value changes frequently from some source, such as a time, price or weather value. Implement an oracle here so that each counterparty's execution of the workstep produces a result that will pass the consistency circuit test and allow the workstep's proof to be deposited in the on-chain merkle trie.

### Judging Criteria
One submission will win the bounty and be judged on the creativity and ingenuity of the workflow design, the choice of oracle data to be used, and the way in which the oracle data is used in the business logic. Also, consideration will be given to whether an how a submission offers any advancements to the Baseline Protocol. Because there is much yet to be done on the implementation of the core protocol to accommodate sophisticated, custom business logic -- some of which may require alteration of the zk-circuit components  -- the above considerations are primary, and less important is whether or not the submission can actually build or run.   

Special consideration will be given to projects that utilize oracle-delivered data sources from Google, such as BigQuery, though this is not required. 

### Winner Announcement Date
January 27, 2021

## Additional notes

See conversation about the project at Minute 35 of the July 6 SSC Meeting: https://www.youtube.com/watch?v=JRObURKH_tk  (min 37)

Workflow steps (worksteps) that must calculate using information like time/date lookups must use an oracle.

Proposed: Use the Radish34 purchase order demo and modify it to add a condition where, if a weather variable like temperature (or another high-delta parameter) were to be over "x", then the discount rate on the purchase order would be "y", else "z".  Simple! And demonstrates the need for an Oracle service like Chainlink, because otherwise each baselined system of record would/could generate different results based on slightly different values from the variable source.

The project will need to define a way for a baselined workstep to require an oracle service for a given parameter and to specify exactly the same variable be used in all instances of the workstep function.

**Comment by humbitious** [comment]
From Chainlink team: Two potential approaches to the project.

Example 1: An ERP system says that the manufacturer's package was shipped and arrived in good condition to the retailor. They want to cross-reference this input against BigQuery to make sure that is indeed correct. BigQuery can independently check IoT networks, web APIs, etc to see if the product arrived at the destination on time and if certain conditions were met such as the door was locked the entire route of the shipment and the temperature within the shipping container stayed at a certain temperature.

Chainlink can aggregate the ERP system input and Goggle's BigQuery's input and trigger an alert if there is a deviation or trigger the contract for payment if they match.

This example is more using BigQuery as an alternative data point to reference against internal systems to see if they are aligned. There is a lot of different ways we could go with this design pattern of comparing ERP internal data, BigQuery data, and even include a third data point being external APIs/data providers as a way to adequately validate data.  

Example 2: A manufacturer gets paid based on how quickly they respond to changes in volume demand. Basically, a retail company uses BigQuery to predict next month's volume based on the predicted market demand (taking into account historical numbers, current market events, recent demand, etc). Once the demand for next month is calculated, the manufacturer gets paid based on how fast they respond to the new purchase orders. 

E.g. If they fill the PO within a week of the predicted volume needed for the month then they get paid x, if they fill it within 2 weeks they get paid y, if they fill it after that they get paid z.

Chainlink can relay the BigQuery volume demand to the PO contract and also relay IoT and/web APIs or even use BigQuery again to confirm the PO was filled and arrived on time.

**Comment by jaerith** [comment]
Hi @humbitious,

I was wondering if this project would also be a good opportunity to introduce Baseline to the idea (or, at least, to discuss the idea) of an interface/protocol that exposes a rules engine.  On one hand, I think that the transparency of publishing less-private business rules (published on IPFS, Filecoin, etc.) could help auditing and trust between companies, so that they can understand and evaluate the logic of partner vendors.  Even more, I think that a subset of those less-private rules could introduce common functionality or logic that could then be shared by a number of enterprises.

So, in the case of Example 1, you could have a published RuleTree like the following, where there are common operations 
according to some standard (like 'POPULATED') and custom operators that can be explained in a separate lexicon 
(like 'CHAINLINK_DELIVERY_LOOKUP'):

```
<?xml version="1.0"?>
<RuleTree xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

   <if description="Check for the delivery of a purchase order">
      <criteria op="AND">
         <eval id="pop1">(N.NewSaleOrder) POPULATED</eval>
         <eval id="pop2">(N.NewSaleEAN) POPULATED</eval>
      </criteria>

      <if description="Checking Input Values">
           <criteria op="AND">
               <eval id="coi1">(N.IsDelivered) CHAINLINK_DELIVERY_LOOKUP (N.NewSaleOrder)</eval>
           </criteria>

           <validate err="severe">
               <criteria op="AND">
		   <eval id="coi2">(N.AverageTemp) CHAINLINK_PACKAGE_AVG_TEMP_LOOKUP (N.NewSaleOrder)</eval>			   
                   <eval id="cmp1">(N.AverageTemp) LT (32)</eval>
               </criteria>

               <failure_message>ERROR!  Delivered item did not have an average temperature below 32 degrees F during transport.</failure_message>
           </validate>           
       </if>
   </if>    
    
</RuleTree>
```

The RuleTree above isn't an example of common functionality.  However, there could be a RuleTree that holds the logic of validating a VAT calculation or a RuleTree that can be used as a template to showcase general functionality of a Baseline-oriented service (like Chainlink).  In any case, these published rules could act as a common reference point for understanding business processes and could be another vivid example of how decentralization and commerce can find common ground.

**Comment by danielnorkin** [comment]
@JohannEid - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.
