### ISSUE TITLE
Specifications Writing Initiative

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#92]
Use this as the container for all specific specifications projects.

Here are some helpful details from the OASIS standards team:

- The OASIS Editor's handbook is on Google at https://docs.google.com/document/d/1lTartcAzlqidzrCxuXFFiwdRDKRipqMnNsMS24SZdjg/edit (Part 1 - it is a 4 part document right now.) This was developed for Technical Committee specifications.

Example GitHub:  https://github.com/oslc-op  &   https://github.com/oslc-op/oslc-specs. 

Template for all OASIS documents: The standard metadata is on the cover page and Notices section and then there are some other optional or required sections in the body of the documents themselves. 

Example of use of the OASIS markdown template: https://github.com/oasis-tcs?q=openc2&type=&language=. One of the examples of a document using the template is https://github.com/oasis-tcs/openc2-cloudpubsub/edit/master/cloudpubsub-v1.0-wd01.md

A TC requests a starter document from OASIS. Work out the details - things like the expected file names and eventual URLs for publication, organization of the piece if it is going to have multiple different parts, stuff like that. I OASIS sets up a template that the TC uses to create Committee Specification Drafts. For TC work, at some point, they need to be released for public review (OASIS handles that) and they address any feedback they receive. When the TC reaches the point where they feel the work is complete and no more comments are pending, OASIS runs a Special Majority Vote for them to approve it as a Committee Specification. From there, they get 3 or more statements attesting that a party has implemented the spec and then we release it for a 60-day public review. (This keeps us aligned with WTO guidelines.) After that review completes, OASIS sends out the work to the members of OASIS in a call for consent at the end of which - assuming there are no objections - the work becomes an OASIS Standard.

The key difference for Open Projects is that the first steps - spec drafts and public reviews - don't apply. (Could if you wanted but not required.) Our view is that the work is in constant public review by virtue of being an open project. I give you a template, you all go to work on it and when you reach that magic 'done' point, I run a Special Majority Vote for the Project Governing Board (2/3 or more yes to pass, no more than 1/4 no). From there, if the PGB wants to submit it for OASIS Standard, we kick it off as above: 3 or more statements of use, 60-day public review, call for consent as OASIS standard.

**Comment by Consianimis** [comment]
@humbitious - This epic seems to be redundant. Suggestion to use https://github.com/ethereum-oasis/baseline-roadmap/issues/99 and close #92.
