### ISSUE TITLE
Events Targets

### ISSUE THREAD

**Issue by humbitious** [eea-oasis/baseline-roadmap#93]
Baseline Protocol is about business to business process automation and the expansion of the proper use of the Mainnet in business, both SMBs and the enterprise.  There are blockchain-focused events that any organization in our field needs to participate in. And there are events that will get the story of baselining and the Mainnet to:

* Information Security Officers
* ERP, CRM and SCM Platforms, Solutions Architects and Integrators
* EDI, Procurement, Corporate Treasury and Inventory Management Leaders
* C-Suite Executives (CEO, CMO, CTO, CIO, CISO)

As you discover promising events, even if they are past or too soon to get a speaking slot, put them in comments here.

**Comment by humbitious** [comment]
Google Cloud Next:  July 14, 2020:  https://cloud.withgoogle.com/next/sf

**Comment by chtmorris** [comment]
Gartner Security & Risk Management Summit, November 2-5, 2020
https://www.gartner.com/en/conferences/na/security-risk-management-us

**Comment by humbitious** [comment]
SC Congress (security), June 19, 2020
https://www.sccongressuk.com/speakers2020/

**Comment by kyleellicott** [comment]
Edge Computing World 2020, October 12-13, 2020
[https://www.edgecomputingworld.com/](https://www.edgecomputingworld.com/ )

**Comment by kyleellicott** [comment]
IoT (Internet of Things) World 2020, August 9-12, 2020
[https://tmt.knect365.com/iot-world/](https://tmt.knect365.com/iot-world/)

**Comment by kyleellicott** [comment]
Blockchain For Business Summit, September 1-3, 2020 [https://tmt.knect365.com/blockchain-business-summit/](https://tmt.knect365.com/blockchain-business-summit/)

**Comment by kyleellicott** [comment]
- Enterprise Connect 2020, August 2020, [https://www.enterpriseconnect.com/orlando](https://www.enterpriseconnect.com/orlando)

- Mircosoft Ignite, September/October 2020, [https://www.microsoft.com/en-us/ignite](https://www.microsoft.com/en-us/ignite)

- DevOps Enterprise Summit, November 2020, [https://events.itrevolution.com/us](https://events.itrevolution.com/us)

- CSO50, December 2020, [https://www.csoconference.com/](https://www.csoconference.com/)

**To Watch:**
- VMWorld 2020, [https://www.vmworld.com/en/index.html](https://www.vmworld.com/en/index.html)
- IDC Futurescape 2020, Fall 2020, [https://www.idc.com/events/futurescape](https://www.idc.com/events/futurescape)
- Dell Technologies World, [https://www.delltechnologiesworld.com/index.htm](https://www.delltechnologiesworld.com/index.htm)
- Oracle's OpenWorld - [https://www.oracle.com/openworld/](https://www.oracle.com/openworld/)

**Comment by humbitious** [comment]
Blockchain World Congress:  Aug 24/25, 2020

https://blockchainconferences.org/?gclid=Cj0KCQjwirz3BRD_ARIsAImf7LMijvS8jgnjvsMexiCoIWvkGZt2xIiDjXuBsfHhtnWIbpXtkUeME2EaAo-AEALw_wcB

**Comment by kyleellicott** [comment]
SF Blockchain Week, July 6-10th - [https://sfblockchainweek.io/](https://sfblockchainweek.io/)

Asia Blockchain Summit - [https://abasummit.io/](https://abasummit.io/)

FutureProof - August 1st - [https://community.blockstack.org/futureproof](https://community.blockstack.org/futureproof)

**Comment by humbitious** [comment]
Blockchain Revolution Toronto: July 7, 2020

https://blockchainrevolutionglobal.com/speakers/

**Comment by amirardalan11** [comment]
LA Blockchain Summit October 6-7th. I'm connected with the Draper Goren Goren Hold organizing the event. Great place to speak about Baseline if that's not already been established. https://lablockchainsummit.com/

**Comment by staceyeschneider** [comment]
TAG Blockchain Society: July 23, 2020 (Baseline is the topic for the whole event - will add the link as it is available.)

**Comment by skyminert** [comment]
Berlin Blockchain Week - 8 - 16 September 2020, Berlin, Germany - https://www.blockchainweek.berlin/
