### ISSUE TITLE
Microsoft Azure SQL Integration Kit

### ISSUE THREAD

**Issue by yorkerhodes3** [eea-oasis/baseline-roadmap#98]

**Comment by juanfranblanco** [comment]
@yorkerhodes3 what data will be integrated here?

**Comment by juanfranblanco** [comment]
@yorkerhodes3 @caleteeter @humbitious what are your thoughts of storing all messages between parties in Sql Server using Confidential Computing, and provide an example of ML, or verification, each record could be linked or validated using DID.
